// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3a5-bhPMwlgl_3w7eHt3vAuRfnpP38AM',
    appId: '1:729169247920:web:5237a1310af9b0f1614575',
    messagingSenderId: '729169247920',
    projectId: 'noteswidget-debc2',
    authDomain: 'noteswidget-debc2.firebaseapp.com',
    storageBucket: 'noteswidget-debc2.firebasestorage.app',
    measurementId: 'G-YDQNHH7ZPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDglnZR3URBDJs0XEnHiTm1MpijxM2vimw',
    appId: '1:729169247920:android:ddec94c937108dcc614575',
    messagingSenderId: '729169247920',
    projectId: 'noteswidget-debc2',
    storageBucket: 'noteswidget-debc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmcYXJFd-C312ZMIQEtq1HOUOsA-sN3_E',
    appId: '1:729169247920:ios:c6d32eef2a20447b614575',
    messagingSenderId: '729169247920',
    projectId: 'noteswidget-debc2',
    storageBucket: 'noteswidget-debc2.firebasestorage.app',
    iosBundleId: 'com.ahmadjamil.noteswidgetapp',
  );
}
